name: CI

on:
  push:
  pull_request:
#  schedule:
#    - cron: '9 * * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate HTML

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker
      run: docker -t mydocker .

    - name: Run Docker
      run: docker run -rm mydocker

