name: CI

on:
  push:
  pull_request:
#  schedule:
#    - cron: '9 * * * *'
  workflow_dispatch:

env:
    MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test HTML generator

    steps:
    - uses: actions/checkout@v3

    - name: install requirements
      run: pip install -r requirements.txt -c constraints.txt

    - name: Verify output
      run: pytest test_generator.py
